language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
env:
  - DJANGO_VERSION=1.4.2
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
before_install:
  - pip install -q django==$DJANGO_VERSION
install:
  - python setup.py develop
  - pip install -q coveralls
script:
  - coverage run --source=tz_detect runtests.py
after_success:
  - coveralls
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7
    - python: "2.6"
      env: DJANGO_VERSION=1.8
    - python: "2.6"
      env: DJANGO_VERSION=1.9
    - python: "3.3"
      env: DJANGO_VERSION=1.4.2
    - python: "3.3"
      env: DJANGO_VERSION=1.9
    - python: "3.4"
      env: DJANGO_VERSION=1.4.2
