language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
before_install:
  - pip install -q $DJANGO
install:
  - python setup.py develop
  - pip install -q coveralls
script:
  - coverage run --source=tz_detect runtests.py
after_success:
  coveralls
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "2.6"
      env: DJANGO="Django>=1.8,<1.9"
    - python: "2.6"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "2.6"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.3"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.4"
      env: DJANGO="Django>=1.4,<1.5"
